const theme = {
    fonts: {
        robotoBold: 'Roboto-Bold',
        robotoRegular: 'Roboto-Regular',
        robotoMedium: 'Roboto-Medium',
    },
    fontSizes: {
        buttonText: '15px',
        buttonTextWithSubtext: '14px',
        buttonSubtext: '13px',
        h1: '34px',
        h1Mobile: '26px',
        h2: '32px',
        h2Mobile: '28px',
        h3: '22px',
        h4: '18px',
        pSmall: '14px',
        pSmallMobile: '14px',
        pMedium: '16px',
        pMediumMobile: '14px',
        pLarge: '18px',
        pLargeMobile: '16px',
        input: '16px',
        inputLabel: '14px',
        inputDetail: '14px',
        inputDisabled: '14px',
        inputError: '14px',
        extraSmallInput: '14px',
        extraSmallDropdown: '14px',
        tooltip: '13px',
        textarea: '16px',
        textareaLabel: '14px',
        textareaDetail: '14px',
        textareaDisabled: '14px',
        textareaError: '14px',
        dropdownList: '16px',
        toggleDetail: '15px',
        checkboxDetail: '15px',
        tableText: '14px',
        number: '16px',
        menuText: '14px',
    },
    breakpoints: {
        xs: 360,
        sm: 600,
        md: 768,
        lg: 960,
        xl: 1280,
    },
    columns: {
        column: 64,
        gutter: 29,
        twoColumns: 64 * 2 + 29,
        threeColumns: 64 * 3 + 29 * 2,
        fourColumns: 64 * 4 + 29 * 3,
        fiveColumns: 64 * 5 + 29 * 4,
        sixColumns: 64 * 6 + 29 * 5,
    },
    cursor: {
        grab: 'grab',
        webkitGrabbing: '-webkit-grabbing',
    },
};

export default theme;
