export enum Colors {
    Success = '#2FBDB0',
    Danger = '#DC5F4F',
    Muted = '#8B929C',
    Dark = '#3C4858',
    Gray = '#8B929C',
    DarkGray = '#626C79',
    LightGray = '#C5C8CD',
    Silver = '#DCE3F2',
    LightSilver = '#EFF1F7',
    Primary = '#DC5F4F',
    PrimaryShiny = '#F65C4E',
    SemiDarkPrimary = '#DE5F4A',
    DarkPrimary = '#d85c4d',
    LightPrimary = '#E6A8A4',
    Secondary = '#F9E7E5',
    DarkSecondary = '#F8CFCA',
    LightSecondary = '#fbf0ef',
    ExtraLightSecondary = '#fffcfc',
    White = '#FFFFFF',
    // Blue-Gray
    NavButtonGray = '#CFDCF4',
    NavButtonDarkGray = '#A9BCE7',
    NavButtonLightGray = '#E2E9F7',
    NavButtonExtraLightGray = '#e8edf7',
    Active = '#4270D1',
    DangerText = '#ED5547',
    Black = '#000000',
    BlackAlpha = '#00000000',
    BlackAlphaExtraLight = '#0000001f',
    BlackAlphaLight = '#00000055',
    BlackAlphaMedium = '#00000080',
    BlackAlphaDark = '#000000b8',
    TableDarkGray = '#3B4759',
    TableLightGray = '#F6F7F8',
    MediumSpringGreen = '#22BEB0',
    LightBlue = '#26C6DA',
    Purple = '#AC51B5',
    LightOrange = '#F2A364',
    Teal = '#26C6DA',

    ParagraphDarkGray = '#203049',
    CardDashedBorderGray = '#C3CFEC',
    CardDashedBorderLightGray = '#C2CEEB',
    // Branding
    LogoTeal = Teal,
    // Background
    PrimaryContentBackground = LightSilver,
    BackdropOverlay = BlackAlphaDark,
    // Text shadows
    TextShadowExtraLight = BlackAlphaExtraLight,
    TextShadowLight = BlackAlphaLight,
    TextShadowMedium = BlackAlphaMedium,
}
